---
- name: "Project: User add"
  user:
    name: "{{ p_user }}"
    groups: ["docker"]
    home: "{{ p_homedir }}"
    shell: /bin/zsh
  become: yes
  tags: [ user, user_create ]

- name: "Project: User directory access"
  file:
    path: "{{ p_homedir }}"
    state: directory
    mode: 0750
    owner: "{{ p_user }}"
    group: "{{ p_homedir_group }}"
  tags: [ user, user_create, permissions ]

- name: "Project: check ~/.zshrc exists"
  stat:
    path: "{{ p_homedir }}/.zshrc"
  changed_when: False
  register: p_register_zshrc
  tags: [ user, user_create, zsh ]

- name: "Project: setup simple ~/.zshrc if empty"
  template:
    src: "{{ p_user_zsh_template }}"
    dest: "{{ p_homedir }}/.zshrc"
    owner: "{{ p_user }}"
    group: "{{ p_user_group }}"
  when: not p_setup_zsh and (not p_register_zshrc.stat.exists or p_force_zshrc)
  tags: [ user, user_create, zsh ]

- name: "Project: setup git"
  include_role:
    name: git
  vars:
    git_user: "{{ p_user }}"
  tags: [ user, git ]
  when: p_setup_git

- name: "Project: setup ssh-keys"
  include_role:
    name: ssh-keys
  vars:
    ssh_keys_user: "{{ p_user }}"
  tags: [ user, ssh-keys ]
  when: p_setup_ssh_keys

- name: "Project: setup zsh"
  include_role:
    name: zsh
  vars:
    zsh_user: "{{ p_user }}"
  tags: [ user, zsh ]
  when: p_setup_zsh
