---

# - name: p_domains
#   debug:
#     msg: "\n{{ p_domains | to_nice_yaml(indent=2) }}"

- name: p_domains
  debug:
    msg: "\n{% for domain in p_domains %}{{ domain.domain }}\n{% endfor %}"

# - name: domains_regions
#   debug:
#     msg: "\n{{ domains_regions | to_nice_yaml(indent=2) }}"

- include_tasks: dns_records_cloudflare.yml
  with_items: "{{ p_domains }}"
  when: domain.provider == "cloudflare" and domain.records is defined and (not domain_only is defined or domain.domain == domain_only)
  loop_control:
    loop_var: domain

- include_tasks: dns_records_selectel.yml
  with_items: "{{ p_domains }}"
  when: domain.provider == "selectel" and domain.records is defined and (not domain_only is defined or domain.domain == domain_only) #  or p_dns_provider == "selectel"
  loop_control:
    loop_var: domain
