---
- name: Mkdir config dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ p_user }}"
    group: "{{ p_user_group }}"
  become: yes
  with_items:
    - "{{ p_log_root }}"
    - "{{ p_data }}/nginx/conf.d"
  tags: [config]

- name: Mkdir p_dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ p_user }}"
    group: "{{ p_user_group }}"
  become: yes
  with_items:
    - "{{ p_dirs }}"
  tags: [config]

- name: Write docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ p_root }}/docker-compose.yml"
    owner: "{{ p_user }}"
    group: "{{ p_user_group }}"
  become: yes
  tags: [config, docker, config-docker-compose]

- name: Write update.sh
  template:
    src: update.sh.j2
    dest: "{{ p_root }}/update.sh"
    owner: "{{ p_user }}"
    group: "{{ p_user_group }}"
    mode: "0755"
  tags: [config, config-deploy]
