---
- name: "{{ p_domain}} : Define p_nginx_proxy_to_backend"
  set_fact:
    p_nginx_proxy_to_backend: |
      {% if p_nginx_backend == 'apache' %}
      proxy_pass http://apache;
      {{ p_nginx_proxy_params }}
      # for pass Basic auth from nginx to php-fpm for bitrix
      proxy_set_header REMOTE_USER $remote_user;
      proxy_set_header X-Forwarded-User $remote_user;
      proxy_set_header Authorization $http_authorization;
      {% endif %}

      {% if p_nginx_backend == 'php-fpm' %}
      include {% if p_nginx_engine == 'drupal' %}snippets/fastcgi_drupal.conf{% else %}fastcgi.conf{% endif %};
      fastcgi_pass unix:{{ p_php_socket }};{% endif %}

      {% if p_nginx_backend == 'service' %}
      proxy_pass http://{{ p_nginx_service_host }}{% if p_nginx_service_port is defined %}:{{ p_nginx_service_port }}{% endif %};
      {{ p_nginx_proxy_params }}
      {% endif %}

- name: "{{ p_domain}} : Define p_nginx_location_php"
  set_fact:
    p_nginx_location_php: |
      # need for urls such /index.php
      location ~* ^.+\.php$ {
        {{ p_nginx_proxy_to_backend | indent(2) }}
      }

- name: "{{ p_domain}} : Define p_nginx_location_rewrite"
  set_fact:
    p_nginx_location_rewrite: |
      location @rewrite {
        access_log /var/log/nginx/access.log combined_host;
        access_log /var/log/nginx/access_time.log combined_host_time;

        {{ p_nginx_proxy_to_backend | indent(2) }}

        {% if nginx_cloudflare_log is defined and nginx_cloudflare_log %}
        access_log /var/log/nginx/access.log combined_host;
        access_log /var/log/nginx/access_cloudflare.log combined_host_cloudflare;{% endif %}
      }
      # end of @rewrite

- name: "{{ p_domain}} : Define p_nginx_engine_server"
  set_fact:
    p_nginx_engine_server: "{{ lookup('template', 'nginx/engine/' + p_nginx_engine + '.j2') }}"
  when: not p_nginx_engine_server

- name: "{{ p_domain}} : Define p_nginx_config"
  set_fact:
    p_nginx_config: "{% if p_ssl %}https{% else %}http{% endif %}"
  when: not p_nginx_config

- name: "{{ p_domain}} : Define p_nginx_template"
  set_fact:
    p_nginx_template: "nginx/config/{{ p_nginx_config }}.j2"
  when: not p_nginx_template


- name: "{{ p_domain}} : Generate variables"
  set_fact:
    nginx_sites_empty: {}

- name: "{{ p_domain}} : Setup nginx vhost"
  include_role:
    name: nginx-vhosts
  vars:
    nginx_sites: "{{ nginx_sites_empty | combine({
      p_domain_main: { 'template': p_nginx_template }
    }) }}"
    nginx_remove_sites: "{{ p_domains_remove }}"

- name: "{{ p_domain}} : Ensure Diffie-Helmann parameters dhparam.pem exists when ssl site provisioned"
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  args:
    creates: /etc/ssl/certs/dhparam.pem
  when: p_ssl
