---
- name: define _p_php_fpm_overrided
  set_fact:
    _p_php_fpm_overrided:
      name: "{{ p_user }}"
      user: "{{ p_php_user }}"
      group: "{{ p_php_group }}"
      listen: "{{ p_php_socket }}"
      listen.owner: "{{ p_apache_user }}"
      listen.group: "{{ p_apache_user }}"
      chdir: /

- name: define _p_php_fpm
  set_fact:
    _p_php_fpm: "{{ (p_php_fpm_defaults|default(dict())) | combine(_p_php_fpm_overrided) | combine(p_php_fpm_extras|default(dict())) }}"

# from https://github.com/NBZ4live/ansible-php-fpm
- name: "{{ p_domain}} : Add pool.d configuration"
  template:
    src: php/pool.conf.j2
    dest: "{{ p_php_fpm_pool_d }}/{{ p_user }}.conf"
  with_items:
    - "{{ _p_php_fpm }}"
  notify:
   - reload php-fpm
