---
- name: "Configuring cron tasks"
  cron:
    cron_file: "{{ item.cron_file | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(p_user) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  with_items: "{{ p_cron_tasks }}"
  tags: [ cron ]

- name: "Configuring cron variables"
  cronvar:
    name: "{{ item.name | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    backup: "{{ item.backup | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    user: "{{ item.user | default(p_user) }}"
  with_items: "{{ p_cron_vars }}"
  tags: [ cron ]
