---
- name: "{{ domain.domain }} : Ensure zone settings of domain (Cloudflare)"
  cloudflare_zone:
    domain: "{{ domain.domain }}"
    state: "{{ domain.state | default('present') }}"
    account_email: "{{ p_dns_cloudflare_email | default(omit) }}"
    api_token: "{{ p_dns_cloudflare_token }}"
    security_level: "{{ domain.security_level | default(omit) }}"
#  delegate_to: localhost
  delegate_to: localhost
  register: _p_dns_cf_output
#  with_items: "{{ domain.records }}"
#  loop_control:
#    loop_var: record
